### ISSUE TITLE
Telstra.com.au

### ISSUE THREAD

**Issue by gyCfjSnO** [travisboss/Jefe-Lists#2]
Hi,

Telstra.com.au is incorrectly on Jefe Blocklist Ticked.

Telstra is the number # 1 telco provider in Australia.

https://en.wikipedia.org/wiki/Telstra

Cheers

**Comment by travisboss** [comment]
Thanks, I will look in to this Monday.

**Comment by travisboss** [comment]
Should be updated now, make sure to pull down latest. #1
