### ISSUE TITLE
Whitelist / Allowlist isn't valid.

### ISSUE THREAD

**Issue by DevShubam** [travisboss/Jefe-Lists#3]
Whitelist / Allowlist doesn't use the ABP Syntax correctly.

Here is how it is currently formatted
`@@example.com`

Although, for it to work it must be as follows:

`@@||example.com`

**Comment by travisboss** [comment]
Just tested this with `@@` and no `||` within a adguard home instance and it still allows the domain to pass unblocked, so the list appears to be valid.
